### ISSUE TITLE
USER STORY: Install basic dependencies

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#16]
As a **developer**, I can **install basic dependencies for the project** so that **the development environment is set up properly, and I can start project development.

Linked to [Epic 1](https://github.com/mtopircean/essentials-by-livia/issues/9)

###Acceptance Criteria

- [x] The development environment has all necessary dependencies installed.
- [x] There are no unfixed errors during setup process
- [x] Deployment by python3 runserver returns adequate page

### Tasks

- [x] Create repo in Github
- [x] Install the CI repo environment.
- [x] Install required applications and store in requirements.
- [x] Create envy file.
- [x] Link to Cloudinary.
