### ISSUE TITLE
USER STORY: Create a document hierarchy and structure

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#18]
As a **developer**, I can **create a clear document hierarchy and document structure in IDE environment** so that **project-related documents and information are well-organized and easily accessible for myself and future developers working on the project**.

Linked to [Epic 1](https://github.com/mtopircean/essentials-by-livia/issues/9)

###Acceptance Criteria

- [x] A clear and organized document hierarchy is achieved
- [x] Documentation structure should include all documentation required for deployment, testing, maintenance and future upgrades

###Task

- [x] Create the structure aligned to CI guidelines and code-along classes.
- [x] Populate with key documents.
