### ISSUE TITLE
USER STORY: Create database structure

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#19]
As a **developer**, I can **define the database schema and create necessary tables and relationships between them** so that **the application can store and manage data appropriately**.

Linked to [Epic 2](https://github.com/mtopircean/essentials-by-livia/issues/10)

###Acceptance Criteria

- [x] The database schema must be defined with appropriate tables and relationships.

###Tasks

- [x] Define main database elements.
- [x] Define the relationship between them.
