### ISSUE TITLE
USER STORY: Create models

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#20]
As a **developer**, I can **create database models for major requirements in the application** so that **data can be accessed, rendered and manipulated within the system**.

Linked to [Epic 2](https://github.com/mtopircean/essentials-by-livia/issues/10)

###Acceptance Criteria

- [x] Database models for all major requirements in the application are created.
- [x] Models should include necessary fields and validation rules.

###Tasks

- [x] Create models for product database
- [x] Create models for product promotion database
- [x] Create models for favorites
- [x] Create models for user database
