### ISSUE TITLE
USER STORY: Create homepage

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#22]
As a **user**, I can **access a visually pleasing and user-friendly homepage** so that **I can navigate with ease and find relevant and useful information**.

Linked to [Epic 3](https://github.com/mtopircean/essentials-by-livia/issues/11)

###Acceptance Criteria

- [x] The homepage must have a visually pleasing and user-friendly interface.
- [x] Important information and navigation elements should be clearly identifiable and represented.

###Tasks

- [x] Create header
- [x] Create footer
- [x] Create base structure
- [x] Connect all to index
- [x] Create index section structure
- [x] Populate with content
