### ISSUE TITLE
USER STORY: Create promotions page

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#23]
As a **user**, I can ** access and view promo material in a dedicated page** so that **I can stay up to date about ongoing offers and deals**.

Linked to [Epic 3](https://github.com/mtopircean/essentials-by-livia/issues/11)

###Acceptance Criteria

- [x] The promotions page must display relevant and up to date promo data.
- [x] Users should be able to navigate through promotions with ease.

###Tasks

- [x] Create structure
- [x] Complete styling including CSS
- [x] Place dummy information for visualization support
