### ISSUE TITLE
USER STORY: Create template for header, footer, and modals

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#24]
As a **user**, I can **interact with clear and visual appealing header, footer, and modal templates across the application** so that **I have a pleasant and intuitive browsing experience**.

Linked to [Epic 3](https://github.com/mtopircean/essentials-by-livia/issues/11)

###Acceptance Criteria

- [ ] Consistent header, footer, and modal templates must be designed and applied across the application.
- [ ] Templates should provide an intuitive and pleasant user experience.

###Tasks

- [x] Create template for header
- [x] Create template for footer
- [x] Test that it can be carried over in other pages
- [x] Create modal template
