### ISSUE TITLE
USER STORY: Create recommendation tool layout

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#25]
As a **user**, I can **receive relevant product recommendations by searching ailments and product names in a visually appealing layout** so that **I can easily find the solution to my search criteria**.

Linked to [Epic 3](https://github.com/mtopircean/essentials-by-livia/issues/11)

###Acceptance Criteria

- [x] The recommendation tool layout must present relevant products based on user input.
- [x] Recommendations should update with growth of product database.

###Task
- [x] Create layout
- [x] Create search bar
- [x] Create filter section
- [x] Create product details
