### ISSUE TITLE
USER STORY: Create registration form

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#26]
As a **user**, I can **submit request to register in order to access the recommendation tool or to join the team using a functional contact form** so that **I can communicate with the application administrators/owner**.

Linked to [Epic 3](https://github.com/mtopircean/essentials-by-livia/issues/11)

###Acceptance Criteria

- [x] A functional contact form must be designed, allowing users  to request access to the recommendation tool or to join the team.
- [x] Form submissions should be stored and accessible to administrators.

###Tasks

- [x] Create form template
