### ISSUE TITLE
USER STORY: Create error pages

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#27]
As a **user**, I can **receive helpful notifications and solutions when encountering errors on the website**, so that **I can have a better user experience**.

Linked to [Epic 3](https://github.com/mtopircean/essentials-by-livia/issues/11)

###Acceptance Criteria

- [x] Custom error pages 404, 403, 500 are designed and implemented.
- [x] Error pages should provide helpful information and guidance to users.

###Tasks

- [x] Import base in 404, 403, 500.
- [x] Create 404 and customize
- [x] Create 403 and customize.
- [x] Create 500 and customize.
