### ISSUE TITLE
USER STORY: Create a user account

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#29]
As a **user**, I can **create a user account with required details** so that **I can access the recommendation and request to join the dottera team**.

Linked to [Epic 4](https://github.com/mtopircean/essentials-by-livia/issues/12)

###Acceptance Criteria

- [x] Users should be able to fill out the registration form with necessary details.
- [x] When request is submitted, a new user account needs to be created and stored securely in the database accessible to the administrator.

###Tasks

- [x] Create registration page linked to login modal
- [x] Push user data into database
- [x] Pull user data into a Profile page where the user can access it
