### ISSUE TITLE
USER STORY: Access a user account - user

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#30]
As a **user**, I can **log into my account using valid credential data** so that **I can access my account data, use the recommendation tool and store favorites**.

Linked to [Epic 4](https://github.com/mtopircean/essentials-by-livia/issues/12)

###Acceptance Criteria

- [x] Users should be able to log in with their registered email/username and password.
- [x] Upon successful login, users should be able to access the exclusive registered user data.

###Tasks

- [x] Create login modal that accepts user credentials
- [x] Create profile page pulling logged user details
- [x] Display key user data in Profile
