### ISSUE TITLE
USER STORY: Update a user account - user

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#31]
As a **user**, I can **update my account information**, so that **I can keep my account details up to date**.

Linked to [Epic 4](https://github.com/mtopircean/essentials-by-livia/issues/12)

### Acceptance Criteria

- [x] Users should be able to access and edit their account information.
- [x] Changes made to the account information should be saved and transferred to the database.

### Tasks
- [x] Create editable element fields in profile page and option to save the changes and push to database
- [x] Create custom forgot passwords, change password, unknown user pages, linked to allauth standard forms
