### ISSUE TITLE
USER STORY: Delete a user account - user

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#32]
As a **user**, I can **delete my account and data from the system** so that **my information is removed from the website website and database**.

Linked to [Epic 4](https://github.com/mtopircean/essentials-by-livia/issues/12)

###Acceptance Criteria

- [x] Users should have the option to delete their account from the manage account page.
- [x] After request and confirmation from user, data is deleted from database and website.

###Tasks

- [x] Create delete option in user account profile
- [x] Create warning and validation requirement as critical action
