### ISSUE TITLE
USER STORY: View user accounts

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#35]
As an **administrator**, I can **view a list of user accounts and their details in the admin page** so that **I can moderate and manage user accounts and requests as needed**.

Linked to [Epic 4](https://github.com/mtopircean/essentials-by-livia/issues/12)

###Acceptance Criteria

- [x] The admin interface should display a list of  user accounts with relevant details.
- [x] Administrators should be able to search and filter users by relevant criteria like(name, email,....).

###Tasks

- [x] Pull user account data in AddUser model/Section in admin
- [x] Setup display data in admin to pull relevant user elements
