### ISSUE TITLE
USER STORY: Update user accounts -admin

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#36]
As an **administrator**, I can **modify user account details in the admin page** so that **I can support users with account-related issues and account maintenance**.

Linked to [Epic 4](https://github.com/mtopircean/essentials-by-livia/issues/12)

###Acceptance Criteria

- [x] Administrators will have the ability to edit user account information from the admin page.
- [x] Changes made to user accounts should be transferred to database when changes are confirmed.

###Tasks

- [x] Setup display data in admin to pull relevant user elements and give admin option to edit and save
