### ISSUE TITLE
USER STORY: Edit promotion

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#41]
As an **administrator**, I can **edit existing promotions to update information** so that **users will view accurate and up-to-date promotion details**.

Linked to [Epic 5](https://github.com/mtopircean/essentials-by-livia/issues/13)

###Acceptance Criteria

- [x] Administrators should be able to modify promotion details in public page
- [x] Administrators should be able to modify promotion details in admin section
- [x] Administrators should be able to modify promotions using the import export admin functionality

###Task
- [x] Functionality in backend supports edit of promotions via both manual and import-export input
- [x] Admin can edit and save promotions from front-end
