### ISSUE TITLE
USER STORY: Add promotion

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#42]
As an **administrator**, I can **add new promotions to the platform** so that **users can view up to date promotions on dottera products**.

Linked to [Epic 5](https://github.com/mtopircean/essentials-by-livia/issues/13)

###Acceptance Criteria

- [x] Administrators should be able to add promotions from the admin interface by filling in relevant fields
- [x] Administrators should be able to add promotions from the admin interface by using the import-export admin function

###Tasks
- [x] Link front to back-end functionality so upload database
- [x] Add promotion manual in back-end
- [x] Add promotion via import-export in back-end
