### ISSUE TITLE
USER STORY: Delete promotion

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#43]
As an **administrator**, I can delete promotions from the platform** so that **expired offers are no longer visible to users**.

Linked to [Epic 5](https://github.com/mtopircean/essentials-by-livia/issues/13)

###Acceptance Criteria

- [x] Administrators should have the option to delete promotions from promotion page.
- [x] Administrators should have the option to delete promotions from admin page.
- [x] When deleted, the promotion should no longer be visible to users.

###Tasks
- [x] Add functionality for the user to be able to delete promotion from front when logged as admin
- [x] Add functionality for the user to be able to delete promotion from back when logged as admin
