### ISSUE TITLE
USER STORY: Search products by ailment

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#46]
As a **user**, I can **search for products based on specific ailments or health conditions, so that **I can find products based my needs**.

Linked to [Epic 6](https://github.com/mtopircean/essentials-by-livia/issues/14)

###Acceptance Criteria

- [x] Users should be able to enter ailment keywords into a search bar.
- [x] Search results should display relevant products related to their ailment.

###Tasks

- [x] Implement search-bar where users can search the ailments they want to apply to their search
