### ISSUE TITLE
USER STORY: Filter products by ailment

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#47]
As a **user**, I can **filter products based on specific ailments**, so that **I can filter down options and make relevant product choices**.

Linked to [Epic 6](https://github.com/mtopircean/essentials-by-livia/issues/14)

###Acceptance Criteria

- [x] Users should have filter options that allow them to select specific ailments.
- [x] Filtered results should constantly update based on the selected ailment(s).

###Tasks

- [x] Implement a check box and apply functionality that returns only relevant and selected searches
