### ISSUE TITLE
USER STORY: Save product to favorites

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#49]
As a **user**, I can **save products to my favorites list for fast access**, so that **I can return to my selected choices whenever I require**.

Linked to [Epic 6](https://github.com/mtopircean/essentials-by-livia/issues/14)

###Acceptance Criteria

- [x] Users should see a "Add to Favorites" button on each product page.
- [x] Clicking the button should add the product to the user's favorites list.

###Tasks

- [x]  Add a favorite button that toggles when click between add and remove
- [x] Create js function to manage it
- [x] Create favorite section is users profile
- [x] Push data in that particular profile section
