### ISSUE TITLE
USER STORY: Remove products from favorites

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#50]
As a **user**, I can **remove products to my favorites list **, so that **I won`t see anymore the products that I no longer want to follow**.

Linked to [Epic 6](https://github.com/mtopircean/essentials-by-livia/issues/14)

###Acceptance Criteria

- [x] Users should see a "Remove from Favorites" button next to each product in their favorites list.
- [x] Clicking the button should remove the product from the user's favorites list.

###Tasks

- [x] Update favorite button so when remove favorite is clicked product is removed from profile page and toggle updated
