### ISSUE TITLE
USER STORY: Modify product

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#53]
As an **administrator**, I can **edit existing product details, allowing me to update product information** so that **users have constant access to up do date and correct product details**.

Linked to [Epic 6](https://github.com/mtopircean/essentials-by-livia/issues/14)

###Acceptance Criteria

- [x] Administrators should be able to modify product details in the admin interface.
- [x] Administrators should be able to modify product details in the product interface.
- [x] Changes made to products should be reflected in the product page.

###Task
- [x] Ailments, price, description and product name can be changed in the admin interface, manual each section
- [x] Ailments, price, description and product name can be changed in the admin interface, by excel import
- [x] From front end users can update the description
