### ISSUE TITLE
USER STORY: Delete product

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#54]
As an **administrator**, I can **remove products from the website,** so that **irrelevant or discontinued products are no longer visible to users**.

Linked to [Epic 6](https://github.com/mtopircean/essentials-by-livia/issues/14)

###Acceptance Criteria

- [x] Administrators should have the option to delete products.
- [x] After deletion, the product should no longer be visible to users and removed from the database.

###Tasks
- [x] Admin can delete a product from admin view
- [x] Admin can delete a product from front page
