### ISSUE TITLE
USER STORY: Testing

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#55]
As a **developer**, I can **perform testing of application's features, functionalities, and performance** so that **users can benefit from a good visual and user experience with minimal bugs**.
Linked to [Epic 7](https://github.com/mtopircean/essentials-by-livia/issues/15)

### Acceptance Criteria

- [ ] Unit test and manual test should be implemented and run successfully.
- [ ] Bugs and issues identified during testing should be documented as identified and fixed or documented as not fixed.

### Task

- [ ] Create functional testing document
- [ ] Create unittest for views
