### ISSUE TITLE
USER STORY: Create about me page

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#57]
As a **user**, I can ** access and view an about website creator dedicated page** so that **I can learn more about the owner and increase my confidence in the quality of the material present on the website**.

Linked to [Epic 3](https://github.com/mtopircean/essentials-by-livia/issues/11)

###Acceptance Criteria

- [x] About the user page should contain clear information and media material about the owner of the page

###Task

- [x] Create the sections in the page.
- [x] Populate the sections with text and media content.
