### ISSUE TITLE
USER STORY: Create about oils page

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#58]
As a **user**, I can ** access and view information about essential oils in a dedicated page** so that **I can learn more about how they are made and used**.

Linked to [Epic 3](https://github.com/mtopircean/essentials-by-livia/issues/11)

###Acceptance Criteria

- [x] The about oils page should contain informative information about the typology of products.
- [x] Page should be easy to read and understand.

###Tasks

- [x] Create page structure.
- [x] Populate with relevant content.
