### ISSUE TITLE
USER STORY: Create user account page

### ISSUE THREAD

**Issue by mtopircean** [mtopircean/essentials-by-livia#59]
As a **user**, I can **interact with clear and visual appealing account oage** so that **I can visualize and modify my user data**.

Linked to [Epic 3](https://github.com/mtopircean/essentials-by-livia/issues/11)

###Acceptance Criteria

- [x] User can access his account information
- [x] User has the option to modify his account information
-
###Tasks

- [x] Create the user page with easy to read key data
- [x] Page has edit button for users to be able to modify the content
